
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres_auth_user
      POSTGRES_PASSWORD: 123456AuthUser
      POSTGRES_DB: authUser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
